"""Add AdminAction table for audit logging

Revision ID: 7b294aaa24bb
Revises: 59aa20133525
Create Date: 2025-08-14 14:34:57.149875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b294aaa24bb'
down_revision = '59aa20133525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_actions', schema=None) as batch_op:
        batch_op.create_index('idx_admin_actions_target', ['target_type', 'target_id'], unique=False)
        batch_op.create_index('idx_admin_actions_type_date', ['action_type', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_actions_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_actions_admin_user_id'), ['admin_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_actions_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_actions_created_at'))
        batch_op.drop_index(batch_op.f('ix_admin_actions_admin_user_id'))
        batch_op.drop_index(batch_op.f('ix_admin_actions_action_type'))
        batch_op.drop_index('idx_admin_actions_type_date')
        batch_op.drop_index('idx_admin_actions_target')

    op.drop_table('admin_actions')
    # ### end Alembic commands ###
